import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from "../components/navbar"
import PreHeader from "../components/preHeader";
import Hero from "../components/Hero";
import Menu from "../components/Menu";
import {useSelector} from "react-redux";
export default function Home() {
    const count = useSelector(state => state.counter.value)
  return (
    <div data-theme="emerald" className="min-h-[100vh] ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {count}
        <Hero/>
        <Menu/>

    </div>
  )
}
